### ISSUE TITLE
version 1.2.0-rc crashes a lot

### ISSUE THREAD

**Issue by BAD-AL** [SleepKiller/swbf-unmunge#20]
Crashes on (PC worlds):[cor1.lvl, end1.lvl, geo1.lvl, mus1.lvl, nab2.lvl, pol1.lvl, spa1.lvl, spa2.lvl, spa3.lvl, spa4.lvl,
	spa8.lvl, spa9.lvl, spa_sky.lvl, tan1.lvl, uta1.lvl]

Hangs on (PC worlds):[tat3.lvl ]

Crashes on (PC):[core.lvl, ingame.lvl]
Crashes on (PC Side):[gun.lvl, jed.lvl, tur.lvl]

I looked into these a little and don't yet understand why all the crashing happens.
But I do think these crashes should get fixed before new features come in.

**Comment by PrismaticFlower** [comment]
Yeah these crashes are a pain, I'm not entirely sure what causes them myself. I think it does have something to do with file saving but I'm unsure.

>  But I do think these crashes should get fixed before new features come in.

Definitely, especially since it's the only thing really blocking v1.2 being "done"

**Comment by phantom567459** [comment]
These errors seem to occur with certain collisions, at least with the files I'm using.
Turning off collision handling seems to bypass the errors.

**Comment by BAD-AL** [comment]
I've tested out the latest code on the shipped (PC) world lvl files; the crashes seem to be gone. 
I do still see a hang on tat3.lvl and shell.lvl (as in the previous version). 
For tat3.lvl, it appears to get stuck in model_scene.cpp:: 'reverse_pretransforms()' on 'tat3_bldg_jabba'.

**Comment by BAD-AL** [comment]
With the latest release (1.2.1), the crashes are gone.
