### ISSUE TITLE
Generate model bounding boxes dynamically

### ISSUE THREAD

**Issue by PrismaticFlower** [SleepKiller/swbf-unmunge#5]
Currently I (poorly) use the bounding box from the munged information. It would be nice to instead generate a bounding box for a msh file based off the extent of the visible geometry, this _should_ give better results when using the model in Zero Editor.

**Comment by RepComm** [comment]
I'm needing this functionality for my model tool as well. I can import them just fine, but constructing then from scratch.. I'm not sure how to calculate the rotations properly.

**Comment by PrismaticFlower** [comment]
Unless you have been having issues with another tool I wouldn't worry about getting it perfect. The munger appears to always generate it's own regardless of what you supply it. It only matters for Zero Editor's selection hitbox. Most likely you'll probably be fine to just base it off the geometry's extent and just set the rotation to `1.0(w), 0.0(x), 0.0(y), 0.0(z)`. 

It's what I'm going to try doing first, I'll probably only do it differently if it causes issues in Zero Editor.
