### ISSUE TITLE
v.0.5.x and up can crash on Windows 7

### ISSUE THREAD

**Issue by PrismaticFlower** [SleepKiller/swbf-unmunge#9]
From the report access violation is causing it. Which is strange because if the tool was going to cause an access violation I would expect it to do that regardless of OS. Maybe it isn't the OS doing it, I don't have Windows 7 handy to find out.

A possible candidate for the cause would be the refracted `File_saver` causing it.

**Comment by RepComm** [comment]
I've got a Windows 7, and Visual Studio Community Edition. I'll see what I can come up with.

**Comment by PrismaticFlower** [comment]
Okay I've switched back to using C++ file streams for writing files. Apparently the test version I posted with this changed fixed the issue. However it would be a big help (and good for my peace of mind) if you were still willing to test it to make sure the issue is gone.

**Comment by RepComm** [comment]
Well, I spent a good hour setting up VS 2017 on that slow Windows 7, and I wouldn't want that to go to waste. I'll be install vcpkg later today and running the source.

**Comment by RepComm** [comment]
Oops, I just reread what you said :P
What the heck, I'll run the new one and debug the old one! Why not?

**Comment by PrismaticFlower** [comment]
fixed by 52c3b86
